nome = str(input('Digite seu nome completo:')).strip()
maiusculo = nome.upper()
print(f'O seu nome em maiusculo fica assim: {maiusculo}.')
minusculo = nome.lower()
print(f'O seu nome em minusculo fica: {minusculo}.')
tamanho = len(nome) - nome.count(' ')
print(f'Seu nome tem: {tamanho} letras.')
separa = nome.split()
print('Seu primeiro nome é {} e ele tem {} letras.'.format(separa[0], len(separa[0])))
#primeiro = nome.find(' ')
#print(f'Seu primeiro nome tem: {primeiro} letras.')